name: Deploy Application
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
          targets: wasm32-wasip1 # WebAssembly target 

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
          node-version: '20' # Or your preferred Node.js version     

    - name: Install JavaScript dependencies
      run: npm install # This will install webpack and other dependencies from your package.json

    - name: Build for Fastly
      run: npm run build:fastly  
        
    - name: Deploy to Compute
      uses: fastly/compute-actions@v11
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
