name: Deploy Application
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
          targets: wasm32-wasip1 # WebAssembly target

    - name: Verify Webpack and Webpack-CLI installation
        run: |
          echo "Verifying webpack and webpack-cli existence in node_modules:"
          ls -l node_modules/webpack
          ls -l node_modules/webpack-cli
          echo "Trying npx webpack --version"
          npx webpack --version
          echo "Trying npx webpack-cli --version"
          npx webpack-cli --version      

    - name: Deploy to Compute
      uses: fastly/compute-actions@v11
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
